title: Ayton sport
email: client.aytonbc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site officiel de la marque ayton sport
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ayton.netlify.com/" # the base hostname & protocol for your site, e.g. http://example.com
author: ""
logo: "assets/img/logo_A_ayton_texte_blanc.png"
lang: fr_FR
# Build settings
markdown: kramdown

exclude: 
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
